=== jrincayc/SpaceWars3D/src/data/tags/tag.dtd
<?xml version="1.0" encoding="ISO-8859-1"?>

<!ELEMENT tags (tag*, sun*, texture*)>

<!ELEMENT mass (#PCDATA)>
<!ELEMENT radius (#PCDATA)>

<!ELEMENT link EMPTY>
    <!ATTLIST link
        id CDATA #REQUIRED
        type CDATA #REQUIRED>
        
<!ELEMENT meshLink EMPTY>
    <!ATTLIST meshLink
        id CDATA #REQUIRED>
        
<!ELEMENT textureLink EMPTY>
    <!ATTLIST textureLink
        id CDATA #REQUIRED>


<!ELEMENT location EMPTY>
    <!ATTLIST location
        x CDATA #REQUIRED
        y CDATA #REQUIRED
        z CDATA #REQUIRED>

<!ELEMENT velocity EMPTY>
    <!ATTLIST velocity
        x CDATA #REQUIRED
        y CDATA #REQUIRED
        z CDATA #REQUIRED>
        
<!ELEMENT rotation (#PCDATA)>
        
<!ELEMENT forwardOrientation EMPTY>
    <!ATTLIST forwardOrientation
        x CDATA #REQUIRED
        y CDATA #REQUIRED
        z CDATA #REQUIRED>
        
<!ELEMENT upwardOrientation EMPTY>
    <!ATTLIST upwardOrientation
        x CDATA #REQUIRED
        y CDATA #REQUIRED
        z CDATA #REQUIRED>
        
<!ELEMENT texture EMPTY>
    <!ATTLIST texture
        id CDATA #REQUIRED
        name CDATA #REQUIRED
        width CDATA #REQUIRED
        height CDATA #REQUIRED
        path CDATA #REQUIRED>
        
<!ELEMENT ambientLight EMPTY>
    <!ATTLIST ambientLight
        red CDATA #REQUIRED
        green CDATA #REQUIRED
        blue CDATA #REQUIRED
        alpha CDATA #REQUIRED>
        
<!ELEMENT diffuseLight EMPTY>
    <!ATTLIST diffuseLight
        red CDATA #REQUIRED
        green CDATA #REQUIRED
        blue CDATA #REQUIRED
        alpha CDATA #REQUIRED>
        
<!ELEMENT specularLight EMPTY>
    <!ATTLIST specularLight
        red CDATA #REQUIRED
        green CDATA #REQUIRED
        blue CDATA #REQUIRED
        alpha CDATA #REQUIRED>
        
<!ELEMENT emissionLight EMPTY>
    <!ATTLIST emissionLight
        red CDATA #REQUIRED
        green CDATA #REQUIRED
        blue CDATA #REQUIRED
        alpha CDATA #REQUIRED>
        
<!ELEMENT shininess (#PCDATA)>
        
<!ELEMENT pointLight (location, ambientLight, diffuseLight, specularLight)>

<!ELEMENT material (ambientLight, diffuseLight, specularLight, emissionLight, shininess)>

<!ELEMENT v EMPTY>
    <!ATTLIST v
        x CDATA #REQUIRED
        y CDATA #REQUIRED
        z CDATA #REQUIRED
        u CDATA #REQUIRED
        v CDATA #REQUIRED>
        
<!ELEMENT t EMPTY>
    <!ATTLIST t
        v1 CDATA #REQUIRED
        v2 CDATA #REQUIRED
        v3 CDATA #REQUIRED>
        
<!ELEMENT mesh (v+, t+)>

<!ELEMENT yaw EMPTY>
    <!ATTLIST yaw
        max CDATA #REQUIRED
        acceleration CDATA #REQUIRED>
        
<!ELEMENT roll EMPTY>
    <!ATTLIST roll
        max CDATA #REQUIRED
        acceleration CDATA #REQUIRED>
        
<!ELEMENT pitch EMPTY>
    <!ATTLIST pitch
        max CDATA #REQUIRED
        acceleration CDATA #REQUIRED>
        
<!ELEMENT verticalSlide EMPTY>
    <!ATTLIST verticalSlide
        max CDATA #REQUIRED
        acceleration CDATA #REQUIRED>
        
<!ELEMENT horizontalSlide EMPTY>
    <!ATTLIST horizontalSlide
        max CDATA #REQUIRED
        acceleration CDATA #REQUIRED>
        
<!ELEMENT thrust EMPTY>
    <!ATTLIST thrust
        max CDATA #REQUIRED
        acceleration CDATA #REQUIRED>
        
<!ELEMENT cockpit (meshLink, textureLink)>

<!ELEMENT ship (textureLink, meshLink, yaw, roll, pitch, thrust, verticalSlide, horizontalSlide, material, radius, mass, meshLink, textureLink)>
        
<!ELEMENT sun (mass, radius, textureLink, pointLight, material, rotation)>
    <!ATTLIST sun
        id CDATA #REQUIRED
        name CDATA #REQUIRED>
        
<!ELEMENT planet (mass, radius, textureLink, material, rotation)>
    <!ATTLIST planet
        id CDATA #REQUIRED
        name CDATA #REQUIRED>
        
<!ELEMENT solarMap (gavList)>
    <!ATTLIST solarMap
        id CDATA #REQUIRED
        name CDATA #REQUIRED>
        
<!ELEMENT gravList (gravObject+)>

<!ELEMENT gravObject (link, location, velocity, forwardOrientation, upwardOrientation)>

=== jrincayc/SpaceWars3D/src/data/tags/meshs.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE tags SYSTEM "tag.dtd">
<tags>
  <mesh id="1" name="Test">
    <v x="0.0" y="1.0" z="0.0" u="1" v="0" />
    <v x="-1.0" y="-1.5" z="0.0" u="1" v="0" />
    <v x="0.0" y="-1.0" z="0.5" u="1" v="0" />
    <v x="1.0" y="-1.5" z="0.0" u="1" v="0" />
    <v x="0.0" y="-1.5" z="1.0" u="1" v="0" />
    <t v1="0" v2="1" v3="2" />
    <t v1="2" v2="1" v3="0" />
    <t v1="0" v2="2" v3="3" />
    <t v1="3" v2="2" v3="0" />
    <t v1="0" v2="2" v3="4" />
    <t v1="4" v2="2" v3="0" />
    </mesh>
    <mesh id="2" name="Cockpit">
        <v x="-1" y="0" z="1" u="0" v="0" />
        <v x="-.8" y="0" z="1" u="1" v="0" />
        <v x=".8" y="0" z="1" u="0" v="0" />
        <v x="1" y="0" z="1" u="1" v="0" />
        <v x="-.8" y="1" z="-.4" u="1" v="0" />
        <v x="-.6" y="1" z="-.4" u="1" v="0" />
        <v x=".6" y="1" z="-.4" u="1" v="0" />
        <v x=".8" y="1" z="-.4" u="1" v="0" />
        <v x="-1" y="0" z="-1" u="1" v="0" />
        <v x="1" y="0" z="-1" u="1" v="1" />
        <t v1="1" v2="0" v3="5" />
        <t v1="4" v2="5" v3="0" />
        <t v1="3" v2="2" v3="6" />
        <t v1="3" v2="6" v3="7" />
        <t v1="4" v2="8" v3="9" />
        <t v1="4" v2="9" v3="7" />
    </mesh>
</tags>

=== jrincayc/SpaceWars3D/src/data/tags/maps.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE tags SYSTEM "tag.dtd">
<tags>
    <solarMap id="0" name="Sun with planet">
        <gravList>
            <gravObject>
                <link id="0" type="sun"/>
                <location x="0.0" y="0.0" z="0.0"/>
                <velocity x="0.0" y="-0.05" z="0.0"/>
                <upwardOrientation x="0.0" y="0.0" z="1.0"/>
                <forwardOrientation x="1.0" y="0.0" z="0.0"/>
            </gravObject>
            <gravObject>
                <link id="0" type="planet"/>
                <location x="10000.0" y="0.0" z="0.0"/>
                <velocity x="0.0" y="50.0" z="0.0"/>
                <upwardOrientation x="0.0" y="0.0" z="1.0"/>
                <forwardOrientation x="1.0" y="0.0" z="0.0"/>
            </gravObject>
        </gravList>
    </solarMap>
    <solarMap id="1" name="Sun with 2 planets">
	<gravList>
            <gravObject>
                <link id="0" type="sun"/>
                <location x="0.0" y="0.0" z="0.0"/>
                <velocity x="-0.07" y="-0.05" z="0.0"/>
                <upwardOrientation x="0.0" y="0.0" z="1.0"/>
                <forwardOrientation x="1.0" y="0.0" z="0.0"/>
            </gravObject>
            <gravObject>
                <link id="0" type="planet"/>
                <location x="10000.0" y="0.0" z="0.0"/>
                <velocity x="0.0" y="50.0" z="0.0"/>
                <upwardOrientation x="0.0" y="0.0" z="1.0"/>
                <forwardOrientation x="1.0" y="0.0" z="0.0"/>
            </gravObject>
            <gravObject>
                <link id="0" type="planet"/>
                <location x="0.0" y="20000.0" z="0.0"/>
                <velocity x="70.0" y="0.0" z="0.0"/>
                <upwardOrientation x="0.0" y="0.0" z="1.0"/>
                <forwardOrientation x="1.0" y="0.0" z="0.0"/>
            </gravObject>
        </gravList>
    </solarMap>
    <solarMap id="2" name="Sun with 3 planets and a moon">
 	<gravList>
            <gravObject>
                <link id="1" type="sun"/>
                <location x="0.0" y="0.0" z="0.0"/>
                <velocity x="0.0" y="-5.5" z="0.0"/>
                <upwardOrientation x="0.0" y="0.0" z="1.0"/>
                <forwardOrientation x="1.0" y="0.0" z="0.0"/>
            </gravObject>
            <gravObject>
                <link id="0" type="planet"/>
                <location x="1000.0" y="0.0" z="0.0"/>
                <velocity x="0.0" y="31.0" z="0.0"/>
                <upwardOrientation x="0.0" y="0.0" z="1.0"/>
                <forwardOrientation x="1.0" y="0.0" z="0.0"/>
            </gravObject>
            <gravObject>
                <link id="0" type="planet"/>
                <location x="5000.0" y="0.0" z="0.0"/>
                <velocity x="0.0" y="14.0" z="0.0"/>
                <upwardOrientation x="0.0" y="0.0" z="1.0"/>
                <forwardOrientation x="1.0" y="0.0" z="0.0"/>
            </gravObject>
            <gravObject>
                <link id="1" type="planet"/>
                <location x="9875.0" y="0.0" z="0.0"/>
                <velocity x="0.0" y="5.75" z="0.0"/>
                <upwardOrientation x="0.0" y="0.0" z="1.0"/>
                <forwardOrientation x="1.0" y="0.0" z="0.0"/>
            </gravObject>
            <gravObject>
                <link id="2" type="planet"/>
                <location x="10125.0" y="0.0" z="0.0"/>
                <velocity x="0.0" y="22.75" z="0.0"/>
                <upwardOrientation x="0.0" y="0.0" z="1.0"/>
                <forwardOrientation x="1.0" y="0.0" z="0.0"/>
            </gravObject>
        </gravList>
    </solarMap>
</tags>

=== jrincayc/SpaceWars3D/src/data/tags/sun.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE tags SYSTEM "tag.dtd">
<tags>
    <sun id="0" name="The Sun">
        <mass>100000000.0</mass>
        <radius>1000</radius>
        <rotation>.25</rotation>
        <textureLink id="4"/>
        <pointLight>
            <ambientLight red="1.0" green="1.0" blue="1.0" alpha="1.0" />
            <diffuseLight red="1.0" green="1.0" blue="1.0" alpha="1.0" />
            <specularLight red="1.0" green="1.0" blue="1.0" alpha="1.0" />
            <location x="0" y="0" z="0" />
        </pointLight>
        <material>
            <ambientLight red="0.0" green="0.0" blue="0.0" alpha="1.0" />
            <diffuseLight red="0.0" green="0.0" blue="0.0" alpha="1.0" />
            <specularLight red="0.0" green="0.0" blue="0.0" alpha="1.0" />
            <emissionLight red="1.0" green="1.0" blue="1.0" alpha="1.0" />
            <shininess>0</shininess>
        </material>
    </sun>
    <sun id="1" name="The Sun">
        <mass>1000000.0</mass>
        <radius>200</radius>
        <rotation>.25</rotation>
        <textureLink id="4"/>
        <pointLight>
            <ambientLight red="0.3" green="0.3" blue="0.3" alpha="1.0" />
            <diffuseLight red="1.0" green="1.0" blue="1.0" alpha="1.0" />
            <specularLight red="1.0" green="1.0" blue="1.0" alpha="1.0" />
            <location x="0" y="0" z="0" />
        </pointLight>
        <material>
            <ambientLight red="0.0" green="0.0" blue="0.0" alpha="1.0" />
            <diffuseLight red="0.0" green="0.0" blue="0.0" alpha="1.0" />
            <specularLight red="0.0" green="0.0" blue="0.0" alpha="1.0" />
            <emissionLight red="1.0" green="1.0" blue="1.0" alpha="1.0" />
            <shininess>0</shininess>
        </material>
    </sun>
</tags>

=== jrincayc/SpaceWars3D/src/data/tags/ships.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE tags SYSTEM "tag.dtd">
<tags>
    <ship id="1" name="Fighter">
        <textureLink id="9" />
        <meshLink id="1" />
        <yaw max="10.0" acc="0.25" />
        <pitch max="10.0" acc="0.25" />
        <roll max="10.0" acc="0.25" />
        <thrust max="1000.0" acc="0.1" />
        <verticalSlide max="500.0" acc="0.1" />
        <horizontalSlide max="500.0" acc="0.1" />
        <material>
            <ambientLight red="0.2" green="0.2" blue="0.2" alpha="1.0" />
            <diffuseLight red="1.0" green="1.0" blue="1.0" alpha="1.0" />
            <specularLight red="0.5" green="0.5" blue="0.5" alpha="1.0" />
            <emissionLight red="1.0" green="1.0" blue="1.0" alpha="1.0" />
            <shininess>20</shininess>
        </material>
        <radius>1</radius>
        <mass>1</mass>
        <cockpit>
            <meshLink id="2" />
            <textureLink id="9" />
        </cockpit>
    </ship>
</tags>

=== jrincayc/SpaceWars3D/src/data/tags/textures.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE tags SYSTEM "tag.dtd">
<tags>
	<texture id="0" name="Sun Texture" width="512" height="512" path="sun.raw"/>
	<texture id="1" name="Earth Texture" width="1024" height="512" path="earth.raw"/>
	<texture id="2" name="Mars Texture" width="1024" height="512" path="mars.raw"/>
	<texture id="3" name="Moon Texture" width="1024" height="512" path="moon.raw"/>
	<texture id="4" name="Small Sun Texture" width="128" height="128" path="sun_small.raw"/>
	<texture id="5" name="Small Earth Texture" width="128" height="128" path="earth_small.raw"/>
	<texture id="6" name="Small Mars Texture" width="128" height="128" path="mars_small.raw"/>
	<texture id="7" name="Small Moon Texture" width="128" height="128" path="moon_small.raw"/>
    
    
	<texture id="8" name="Ship Texture" width="1024" height="512" path="ship.raw"/>
	<texture id="9" name="Small Ship Texture" width="1" height="1" path="ship_small.raw" />
 </tags>

=== jrincayc/SpaceWars3D/src/data/tags/planets.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE tags SYSTEM "tag.dtd">
<tags>
    <planet id="0" name="Planet 1">
        <mass>100000.0</mass>
        <radius>100</radius>
        <rotation>1</rotation>
        <textureLink id="5"/>
        <material>
            <ambientLight red="0.4" green="0.4" blue="0.4" alpha="1.0" />
            <diffuseLight red="1.0" green="1.0" blue="1.0" alpha="1.0" />
            <specularLight red="0.5" green="0.5" blue="0.5" alpha="1.0" />
            <emissionLight red="0.01" green="0.01" blue="0.01" alpha="1.0" />
            <shininess>20</shininess>
        </material>
    </planet>
    <planet id="1" name="Planet 2">
        <mass>75000.0</mass>
        <radius>75</radius>
        <rotation>1</rotation>
        <textureLink id="6"/>
        <material>
            <ambientLight red="0.4" green="0.4" blue="0.4" alpha="1.0" />
            <diffuseLight red="1.0" green="1.0" blue="1.0" alpha="1.0" />
            <specularLight red="0.5" green="0.5" blue="0.5" alpha="1.0" />
            <emissionLight red="0.0" green="0.0" blue="0.0" alpha="1.0" />
            <shininess>20</shininess>
        </material>
    </planet>
    <planet id="2" name="Planet 3">
        <mass>25000.0</mass>
        <radius>25</radius>
        <rotation>1</rotation>
        <textureLink id="7"/>
        <material>
            <ambientLight red="0.4" green="0.4" blue="0.4" alpha="1.0" />
            <diffuseLight red="1.0" green="1.0" blue="1.0" alpha="1.0" />
            <specularLight red="0.5" green="0.5" blue="0.5" alpha="1.0" />
            <emissionLight red="0.0" green="0.0" blue="0.0" alpha="1.0" />
            <shininess>20</shininess>
        </material>
    </planet>
</tags>
